#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

cat <<EOF > /etc/nginx/sites-available/default
server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/wwww/html;
	index index.html index.htm;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}

	error_page 404 /404.html;
	location = /404.html {
		root /usr/share/nginx/html;
	internal;
	}
}
EOF

service nginx restart
