#!/usr/bin/env bash
# Double the number of webservers

# Update APT packages
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

#configure firewall to allow requests through port 80
sudo ufw allow 'Nginx HTTP'

# Create directory for web content
sudo mkdir -p /var/www/html

# change permissions to allow easy file creation
sudo chmod -R 755 /var/www

# Create index page
echo 'Hello World!' | sudo tee /var/www/html/index.html

# Create custom 404 Error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Get the hostname
hostname=$(hostname)

# Configure redirect for a single page and add a header to display hostname
string_for_replacment="server_name _;\n\tadd_header X-Server-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com/watch?v=DUv-r_OCoZo permanent;"
sudo sed -i "s/server_name _;/$string_for_replacment/" /etc/nginx/sites-enabled/default

# Configure redirect for 404 error page
string_for_replacment="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacment/" /etc/nginx/sites-enabled/default

# Restart the web server after updating the settings
sudo service nginx restart
