#!/usr/bin/env bash
# This script is dislaying a text sevral times

function sigterm_handler {
	echo "I am invincible!!!"
}
trap sigterm_handler SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
