#!/usr/bin/env bash
# Block all incoming traffic

# Update package lists
sudo apt-get update

# Install ufw if not installed
sudo apt-get install -y ufw

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH, HTTP, and HTTPS
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 433/tcp

# Enable ufw
sudo ufw enable

# Display ufw status to verify rules
sudo ufw status
